services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_ros2_image
    container_name: ros2_container
    volumes:
      - .:/ros2_ws/src_CR
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - QT_X11_NO_MITSHM=1
    privileged: true  
    stdin_open: true
    tty: true
    network_mode: "host"

volumes:
  shared_volume:
