controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController

arm_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 10.0
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01

gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
