name: Build and Compile ROS2 workspace
#add git actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ROS_CI:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        ros2_distribution:
          - humble

        include: 
          # ROS 2 Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
    
    container:
        image: ${{ matrix.docker_image }}
    
    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src


      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout code and setup workspace
        uses: actions/checkout@v4
        with:
          path: ros_ws/src

      - name: Setup git credentials
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: |
            cr_action_server
            cr_interface
            cr_moveit
            cr_vision
            cr_task_orchestration
            cr_scene_management
            